[package]
name = "nyaterm-plugin-gpu"
version = "1.0.1"
edition = "2024"
rust-version = "1.94"

[dependencies]
nyaterm-plugin-sdk = { path = "../../../sdk/rust/nyaterm-plugin-sdk" }
nyaterm-gpu = { path = "../../../../src-tauri/crates/nyaterm-gpu" }
tokio = { version = "1", features = ["macros", "rt"] }
serde_json = "1"
